ci: add -Dno-discarded-qualifiers
...whenever --force-fallback-for=wlroots is used to avoid error

../subprojects/wlroots/xcursor/xcursor.c: In function ‘xcursor_next_path’:
../subprojects/wlroots/xcursor/xcursor.c:605:23: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  605 |         char *colon = strchr(path, ':');
      |                       ^~~~~~