meson: require wlroots 0.13.0 after 15ebd2529477
src/server.c:93:61: error: too few arguments to function call, expected 2, have 1
        server->backend = wlr_backend_autocreate(server->wl_display);
                          ~~~~~~~~~~~~~~~~~~~~~~                   ^
subprojects/wlroots/include/wlr/backend.h:43:21: note: 'wlr_backend_autocreate' declared here
struct wlr_backend *wlr_backend_autocreate(struct wl_display *display,
                    ^
src/xdg.c:180:2: warning: implicit declaration of function 'wlr_xdg_surface_for_each_popup_surface' is invalid in C99 [-Wimplicit-function-declaration]
        wlr_xdg_surface_for_each_popup_surface(view->xdg_surface, iterator, data);
        ^
ld: error: undefined symbol: wlr_xdg_surface_for_each_popup_surface
>>> referenced by xdg.c:180 (src/xdg.c:180)
>>>               labwc.p/src_xdg.c.o:(xdg_toplevel_view_for_each_popup_surface)